### PR TITLE
Added support for Apache Cocoon

### PR DESCRIPTION
**Pull request by PeterMosmans**

### CODE REVIEW

**Comment by adetlefsen-rms** [comment]
Looks good! Thanks @PeterMosmans

**Comment by adetlefsen-rms** [comment]
@PeterMosmans check out the [test code](https://github.com/augustd/burp-suite-software-version-checks/blob/master/test/burp/RegexTest.java) I added. When you add a new pattern you can now add an example version string to [testResponse.txt](https://github.com/augustd/burp-suite-software-version-checks/blob/master/test/burp/testResponse.txt) and run JUnit to make sure it all works. 

Keep sending PRs!

**Comment by PeterMosmans** [comment]
Hi @adetlefsen-rms - thanks for the merge and the testcode. It looks like you could add continuous integration tests :wink: 
Until so far, I'll do the tests manually. PR's incoming :smile:

**Comment by PeterMosmans** [comment]
Hi @adetlefsen-rms - could you please give me some hints with regards to running the tests ? Command line examples, so that I know I'm running the (right) tests correctly. Thanks !

**Pull request merged**
