### PR TITLE
attrs extensionName,tabName => obj var EXTENSION_NAME, TAB_NAME

### PR DESCRIPTION
**Pull request by libcrack**
The extension name shown within Burp suite's tabs `Software Version Reported` is maybe a bit long. It seems that "Target", "Proxy" or "Spider" tabs are 1/3 long in comparison with the Software Version Reported. As a consequence, Burp's tabs panel gets fully bloated when using a small number extensions.

This patch shorts the Software Version Reported tab's name. 

If the full extension name must appear, a solution to keep the show tab name could be to pass the static variable EXTENSION_NAME to `callbacks.issueAlert()`, displaying this way the full extension name in the "Alerts" tab of burp proxy when the extension is loaded. The following excerpt shows an example of this approach:

```java
public class BurpExtender implements IBurpExtender, ... {

    private IBurpExtenderCallbacks callbacks;
    private IExtensionHelpers helpers;

    public static String EXTENSION_NAME = "Software Version Check";
    public static String TAB_NAME = "Versions";   // or Ver. Check,or SoftCheck, or
                                                  // whatever shorter name you prefer
    [...]

    // Implements IBurpExtender 
    @Override
    public void registerExtenderCallbacks(IBurpExtenderCallbacks callbacks) {
        this.callbacks = callbacks;
        helpers = callbacks.getHelpers();
        callbacks.issueAlert(String.format("Loading extension " + EXTENSION_NAME));
        callbacks.setExtensionName(TAB_NAME);

     [...]

    }
```

### CODE REVIEW

**Comment by adetlefsen-rms** [comment]
I'm considering whether this should be a modification to the BaseExtender class: 

https://github.com/augustd/burp-suite-utils/blob/master/src/com/codemagi/burp/BaseExtender.java

Calling `setExtensionName()` will change the name not only in the tab, but also in the list of loaded extensions in the Extender tab.

**Comment by libcrack** [comment]
Fair enough, I can see it on https://github.com/augustd/burp-suite-utils/blob/master/src/com/codemagi/burp/BaseExtender.java:

```java
public abstract class BaseExtender implements IBurpExtender {
    
protected String extensionName = "Base Extension";
```

Shall I close this pull request?

**Comment by adetlefsen-rms** [comment]
If you change it so just line #40 is changed I'll merge it: 

`mTab = new BurpSuiteTab(TAB_NAME, callbacks);`

**Comment by libcrack** [comment]
something like this? :-)

**Comment by augustd** [comment]
Close enough.

**Pull request merged**
