### PR TITLE
Added some javascript-based software

### PR DESCRIPTION
**Pull request by PeterMosmans**
Some more checks for the database :wink: 

I added some trailing whitespace as well

### CODE REVIEW

**Comment by augustd** [comment]
For client-side Javascripts that expose their entire source anyway, the Severity should be set to 'Information'.

**Comment by PeterMosmans** [comment]
Thanks for your feedback. Are you interested in another (new) pull request with the updated information ?

**Comment by augustd** [comment]
Yes please!

**Comment by PeterMosmans** [comment]
Closed, see new Pull Request

**Pull request closed without merging**
